name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
      
    steps:
        
      - uses: actions:checkout@3.1.0
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username:
          password:
