name: HTTP

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{  secrets.USER  }}
          password: ${{  secrets.PASSWORD  }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: |
            itslevictor/docker_ci_cd:v1
            itslevictor/docker_ci_cd:latest
